# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PNyaSCjSd5I3nU-WwoTulo713J43uQva
"""

import sys
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/data_preprocessed.csv')

plt.figure(figsize=(15,10))
sns.countplot(data=df, x='event_type')
plt.title('Event Type Distribution')

plt.figure(figsize=(15,10))
sns.boxplot(y='price', x='category', data=df)
plt.xticks(rotation=90)
plt.title('Price Distribution by Category')

plt.figure(figsize=(15,10))
sns.countplot(data=df, x='price_bin', hue='event_type')
plt.title('Price Bin vs Event Type')

plt.figure(figsize=(15,10))
cols = [
    'event_type',
    'brand',
    'price',
    'category',
    'price_bin'
]

df_heat = df[cols].copy()

df_heat['event_type'] = df_heat['event_type'].astype('category').cat.codes
df_heat['brand'] = df_heat['brand'].astype('category').cat.codes
df_heat['category'] = df_heat['category'].astype('category').cat.codes
df_heat['price_bin'] = df_heat['price_bin'].astype('category').cat.codes

corr = df_heat.corr()

plt.figure(figsize=(10,8))

sns.heatmap(
    corr,
    annot=True,
    fmt=".4f",
    cmap="Blues",
    linewidths=0.5
)

plt.title("Feature Correlation Heatmap")

